name: Auto Deploy HRMS Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Hostinger
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: 65002
          script: |
            cd /home/u787208577/domains/hrmsback.digitalwebguider.com/nodejs

            git fetch origin
            git reset --hard origin/main

            touch tmp/restart.txt

            echo "Backend deployed successfully."
